### ISSUE TITLE
Unable to remap K

### ISSUE THREAD

**Issue by bennyty** [sophacles/vim-processing#36]
Hello Vim-Processing!

Recently I decided that moving with j and k was too slow. So I did:
```
nnoremap J 5gj
nnoremap K 5gk
```
However in .pde files I am unable to move up 5 lines with shift k as this plugin (which I   have thoroughly enjoyed using) is trying to search documentation on K. Is there a way to disable the default mappings? Other plugins provide lines such as:
```
let g:goldenview__enable_default_mapping = 0 " Disable default mappings
```
Could this be provided? If I've overlooked something I'd love to know.

Thank you for your plugin!

**Comment by sophacles** [comment]
Hi @bennyty - the very short term solution to this is to comment out line 86 in `ftplugin/processing.vim`. ( https://github.com/sophacles/vim-processing/blob/master/ftplugin/processing.vim#L86 ) This will prevent K from being remapped.

(BTW vim has some stuff builtin scrolling commands that are related to your remap in `:he scrolling` if you didn't know about it. Not that it changes our absolute remap of `K` being a bug - just something that may help some of your use cases of moving around a document quickly - particularly `CTRL-D` and `CTRL-U` in conjunction the `scroll` and `startofline` options).

The longer term solution for this project is one of:

1. add a variable `g:processing_doc_view` (which defaults to 1). If it is 0, don't do the mapping.

2. have a python script to do the browser opening, and fiddle with `keywordprg` and `iskeyword`

3. different mapping or fiddle with it to (e.g) `<leader>K` or something

@crazymaster - do you have a preference? I'm leaning towards 1, because 2 is going to have weird side-effects and 3 is annoying for most users.

**Comment by crazymaster** [comment]
I recommend to add a variable but use `<Plug>` so that user can map.
I will make the patch.
